### PR TITLE
fix: handle boolean values on axes

### LINKED ISSUE #785: Visualisation Glyphosate 💥
[Glyphosate acheté en France](https://ecologie.data.gouv.fr/indicators/6853d7c4cc7702010ac57d4b)

Visualisation vide.

Noms de colonnes OK.

### PR DESCRIPTION
**Pull request by abulte**
- Fix https://github.com/ecolabdata/ecospheres/issues/785: handle boolean values in axes
- Add debug library (locally or explicitly activated) and debug logs

### CODE REVIEW

File: src/components/mesh.mjs [hunk 1]
```diff
@@ -23,6 +24,8 @@ export function makeMeshDropdown(indicator, possibleMeshes) {
   container.innerHTML = html
   const meshSelect = getMeshSelect(indicator)
   meshSelect.addEventListener('change', () => {
+    const selectedMesh = meshSelect.value
+    debug.log(`📏 Mesh selected: ${selectedMesh}`)
```
Comment (streino) [inline src/components/mesh.mjs]: Nitpick: Not convinced we need the explicit const
```suggestion
    debug.log(`📏 Mesh selected: ${meshSelect.value}`)
```

File: src/components/territory.mjs [hunk 2]
```diff
@@ -50,6 +51,8 @@ export async function makeTerritoryDropDown(indicator) {
     )
     const territorySelect = getTerritorySelect(indicator)
     territorySelect.addEventListener('change', () => {
+      const selectedTerritory = territorySelect.value
+      debug.log(`🗺️ Territory selected: ${selectedTerritory}`)
```
Comment (streino) [inline src/components/territory.mjs]: Nitpick: Same as previous
```suggestion
      debug.log(`🗺️ Territory selected: ${territorySelect.value}`)
```

File: src/core/datasets.mjs [hunk 3]
```diff
@@ -48,11 +49,19 @@ function filterDataByCurrentAxes(indicator, axesNames, data) {
...
-    )
+
+  const filteredData = data.filter((d) =>
+    Object.entries(currentAxes).every(([axe, values]) => {
+      const itemValue = d[axe]
+      // Conversion en string pour gérer aussi les valeurs booléennes
+      const itemValueStr = String(itemValue)
+      const valuesStr = values.map(v => String(v))
+      return valuesStr.includes(itemValueStr)
+    })
```
Comment (streino) [inline src/core/datasets.mjs]: Nitpick: Reads better?
```suggestion
    Object.entries(currentAxes).every(([axe, values]) =>
      // Conversion en string pour gérer aussi les valeurs booléennes
      values.map(String).includes(String(d[axe]))
    )
```

**Review by streino — APPROVED** [review]
